# -*- coding: utf-8 -*-
"""OpenWeather_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNnMWfeWwpIwtdUTkadApPtyQiGwBLAR
"""

import requests
import json

def get_weather(city):
  API_KEY = "자신의 API KEY"
  lang= "kr"
  url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&lang={lang}&units=metric"

  response = requests.get(url)
  data = json.loads(response.text)

  if response.status_code == 200:
    print(f"{city}의 날씨: {data['weather'][0]['description']}")
    print(f"현재 기온: {data['main']['temp']}")
    print(f"체감 온도; {data['main']['feels_like']}")
    print(f"최저 기온: {data['main']['temp_min']}")
    print(f"최고 기온: {data['main']['temp_max']}")
    print(f"습도: {data['main']['humidity']}")
  else:
    print("error")
city_name = input("도시 이름을 입력하세요 (영어로 입력): ")
get_weather(city_name)